version: '3.8'

networks:
  app-network:
    driver: bridge

services:
    mysqldb:
      image: mysql:latest
      container_name: mysqldb
      networks:
        - app-network
      restart: unless-stopped
      env_file: ./.env.prod
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        - MYSQL_DATABASE=$DB_NAME
      ports:
        - $DB_PORT:$DB_PORT
      volumes:
        - db:/var/lib/mysql
      healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root"]
            timeout: 20s
            retries: 10
    phpmyadmin:
      image: phpmyadmin:latest
      restart: unless-stopped
      networks:
        - app-network
      ports:
          - 3307:80
      environment:
          # we specify that we connect to an arbitrary server with the flag below
          # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
          - PMA_ARBITRARY=1
    app:
      depends_on:
        mysqldb:
          condition: service_healthy
      command: npm start
      build: .
      # restart: unless-stopped
      networks:
        - app-network
      volumes:
        - .:/usr/app/
        - /usr/app/node_modules
      ports:
        - $NODE_DOCKER_PORT:$PORT
      env_file: ./.env.prod
      environment:
        - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
        - PORT=$PORT
        - DB_HOST=$DB_HOST
        - DB_USER=$DB_USER
        - DB_NAME=$DB_NAME
        - DB_PORT=$DB_PORT
      stdin_open: true
      tty: true

volumes: 
  db:
  